fix(web): font style
2110366-2566-2/heathub pull request #36
Opened 2024-02-11 03:41 UTC by TeerapatChan

2024-02-11 18:34 UTC, OnFireByte requested changes

2024-02-11 18:34 UTC, OnFireByte commented on src/styles/globals.css
> +    @apply font-sans  text-3xl font-normal lg:text-5xl;
ไม่ต้องใส่ font-sans, font-normal (weight)

2024-02-11 18:34 UTC, OnFireByte commented on src/styles/globals.css
>    }
ไม่ต้องมี

2024-02-11 18:35 UTC, bpremika commented on src/styles/globals.css
> +    @apply font-sans text-base font-medium;
เอา body5, body6 ออกหน่อยคับ

2024-02-11 18:35 UTC, bpremika commented on src/styles/globals.css
>      @apply font-sans text-3xl font-normal;
ละก็ไม่ต้องใส่ font-normal แล้ว

2024-02-12 05:59 UTC, bpremika approved these changes

2024-02-12 06:04 UTC, OnFireByte approved these changes

2024-02-12 06:05 UTC, merged